In [28]:
import numpy as np
import numpy.linalg as la

# One-D Array

In [24]:
x = np.array([1,2,3])
x

array([1, 2, 3])

# Two-D Array

In [30]:
y = np.array([[1,2,3],[4,5,6]])
y.T
x=np.array([[1,2],[3,4]])
la.det(x)

-2.0000000000000004

# Three-D Array

In [120]:
z = np.array([[[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
z

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[-1, -2, -3],
        [-4, -5, -6]]])

# Properties of N-D Array

In [ ]:
print(z)
print(z.shape)
print(z.ndim)
print(z.dtype)
print(z.size)
print(z.nbytes)
a = np.transpose(z,(0,2,1))
print(a)
a = np.transpose(a,(1,0,2))
print(a)
b = np.transpose(z,(2,1,0))
print(b)
print(z.T)

# Numpy Constant

In [ ]:
print(np.inf)
print(np.NINF)
print(np.NAN)
print(np.NZERO)
print(np.PZERO)

print(np.e)
print(np.euler_gamma)
print(np.pi)

# Ones and Zeros

In [130]:
x = np.empty([3,3],np.uint16)
x

array([[ 8805,  8762, 30821],
       [25445, 29813, 24421],
       [25970, 30065, 29541]], dtype=uint16)

In [109]:
x = np.eye(5,dtype=np.uint8)
x

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

In [113]:
x=np.eye(5,dtype=np.uint8,k=1)
x

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [117]:
x=np.identity(5,dtype=np.uint8)
x

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

In [126]:
x=np.ones([3,3,3],dtype=np.uint8)
x

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=uint8)

In [122]:
x=np.zeros([5,5],dtype=np.uint8)
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [131]:
x=np.full((5,5),dtype=np.uint8,fill_value=10)
x

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]], dtype=uint8)

# Matrix Creation Routines

In [5]:
x = np.tri(5,5,k=-1,dtype=np.uint16)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [9]:
x = np.ones((5,5),dtype=np.uint16)
y = np.tril(x,k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [31]:
x = np.ones((5,5),dtype=np.uint16)
y=np.triu(x,k=1)
print(y)

[[0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [121]:
x = np.array([[1,2],[3,4]],np.uint8)
print(la.det(x))
print(la.inv(x))
print(np.round(np.dot(x,la.inv(x))))
print(la.eig(x))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


# Random

In [127]:
x = np.random.normal(size=4)  #radnom.normal/uniform
print(x)

[-1.16313579  0.65203935  0.34310496  0.10420682]


In [129]:
x = np.random.randint(low = 1,high = 10, size = 5)
print(x)

[3 9 6 4 9]


In [226]:
x = np.random.rand(3,3)
print(x)

[[6.40770767e-02 7.79456408e-01 6.43661935e-01]
 [5.99565061e-01 7.71709345e-01 8.90591916e-01]
 [1.09402397e-02 1.34114576e-04 6.55436674e-01]]


In [228]:
x = np.random.normal(0,2,10)
print(x)

[ 1.84850705 -0.63264193  0.44984268 -3.46749593 -3.2234627   0.40363955
 -2.34372868  1.66437535  1.38443796  0.99729357]


# Array Manipulation Routines

In [133]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [141]:
y = x.reshape((3,2))    # or you can do with other syntax y = np.reshape(x,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [137]:
x = np.array([[1,2,3],[4,5,6]],np.uint8)
print(x)

[[1 2 3]
 [4 5 6]]


In [143]:
y = np.reshape(x,6)
print(y)

[1 2 3 4 5 6]


In [170]:
y = x.ravel()  # other syntax np.racel(x)
print(y)

[1 2 3 4 5 6]


In [152]:
y = x.flatten('C')
print(y)

[1 2 3 4 5 6]


In [171]:
y = x.flatten('F')
print(y)

[1 4 2 5 3 6]


In [176]:
x = np.array([1,2,3],np.uint8)
y = np.array([4,5,6],np.uint8)
z = np.stack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [179]:
z= np.stack((x,y),axis=0)
print(z)

[[1 2 3]
 [4 5 6]]


In [181]:
z= np.stack((x,y),axis=1)  # for axis = -1 it will give the same output
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [183]:
z = np.dstack((x,y))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [185]:
z = np.hstack((x,y))
print(z)

[1 2 3 4 5 6]


In [187]:
z = np.vstack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [194]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [197]:
a,b,c = np.split(x,3)
print(a)
print(b)
print(c)

[0 1 2]
[3 4 5]
[6 7 8]


In [232]:
x = np.random.rand(4,4,4)
print(x)

[[[0.5751142  0.97912233 0.93256729 0.18172034]
  [0.5564332  0.59162577 0.9294581  0.38454236]
  [0.62499918 0.10851299 0.83121866 0.45613941]
  [0.17952721 0.47913767 0.89873026 0.34462523]]

 [[0.91726177 0.01036594 0.6459295  0.84001229]
  [0.71497769 0.85665516 0.85462264 0.20167321]
  [0.02860571 0.01699557 0.9816342  0.88939763]
  [0.60690178 0.9698497  0.99770709 0.31927425]]

 [[0.60484186 0.43502748 0.13859491 0.00628637]
  [0.15159298 0.25986192 0.16676358 0.11380128]
  [0.82142181 0.8921145  0.30563692 0.68065345]
  [0.56686112 0.63545784 0.50748191 0.95516412]]

 [[0.61579189 0.41850701 0.6426856  0.45839306]
  [0.06968443 0.01902491 0.37600027 0.88664314]
  [0.45929152 0.12146519 0.23087077 0.25836046]
  [0.91518702 0.53411372 0.57493867 0.22082032]]]


In [233]:
a,b = np.split(x,2)
print(a)
print(b)
print(a.shape)

[[[0.5751142  0.97912233 0.93256729 0.18172034]
  [0.5564332  0.59162577 0.9294581  0.38454236]
  [0.62499918 0.10851299 0.83121866 0.45613941]
  [0.17952721 0.47913767 0.89873026 0.34462523]]

 [[0.91726177 0.01036594 0.6459295  0.84001229]
  [0.71497769 0.85665516 0.85462264 0.20167321]
  [0.02860571 0.01699557 0.9816342  0.88939763]
  [0.60690178 0.9698497  0.99770709 0.31927425]]]
[[[0.60484186 0.43502748 0.13859491 0.00628637]
  [0.15159298 0.25986192 0.16676358 0.11380128]
  [0.82142181 0.8921145  0.30563692 0.68065345]
  [0.56686112 0.63545784 0.50748191 0.95516412]]

 [[0.61579189 0.41850701 0.6426856  0.45839306]
  [0.06968443 0.01902491 0.37600027 0.88664314]
  [0.45929152 0.12146519 0.23087077 0.25836046]
  [0.91518702 0.53411372 0.57493867 0.22082032]]]
(2, 4, 4)


In [234]:
a,b = np.vsplit(x,2)
print(a)
print(b)
print(a.shape)

[[[0.5751142  0.97912233 0.93256729 0.18172034]
  [0.5564332  0.59162577 0.9294581  0.38454236]
  [0.62499918 0.10851299 0.83121866 0.45613941]
  [0.17952721 0.47913767 0.89873026 0.34462523]]

 [[0.91726177 0.01036594 0.6459295  0.84001229]
  [0.71497769 0.85665516 0.85462264 0.20167321]
  [0.02860571 0.01699557 0.9816342  0.88939763]
  [0.60690178 0.9698497  0.99770709 0.31927425]]]
[[[0.60484186 0.43502748 0.13859491 0.00628637]
  [0.15159298 0.25986192 0.16676358 0.11380128]
  [0.82142181 0.8921145  0.30563692 0.68065345]
  [0.56686112 0.63545784 0.50748191 0.95516412]]

 [[0.61579189 0.41850701 0.6426856  0.45839306]
  [0.06968443 0.01902491 0.37600027 0.88664314]
  [0.45929152 0.12146519 0.23087077 0.25836046]
  [0.91518702 0.53411372 0.57493867 0.22082032]]]
(2, 4, 4)


In [235]:
a,b = np.hsplit(x,2)
print(a)
print(b)
print(a.shape)

[[[0.5751142  0.97912233 0.93256729 0.18172034]
  [0.5564332  0.59162577 0.9294581  0.38454236]]

 [[0.91726177 0.01036594 0.6459295  0.84001229]
  [0.71497769 0.85665516 0.85462264 0.20167321]]

 [[0.60484186 0.43502748 0.13859491 0.00628637]
  [0.15159298 0.25986192 0.16676358 0.11380128]]

 [[0.61579189 0.41850701 0.6426856  0.45839306]
  [0.06968443 0.01902491 0.37600027 0.88664314]]]
[[[0.62499918 0.10851299 0.83121866 0.45613941]
  [0.17952721 0.47913767 0.89873026 0.34462523]]

 [[0.02860571 0.01699557 0.9816342  0.88939763]
  [0.60690178 0.9698497  0.99770709 0.31927425]]

 [[0.82142181 0.8921145  0.30563692 0.68065345]
  [0.56686112 0.63545784 0.50748191 0.95516412]]

 [[0.45929152 0.12146519 0.23087077 0.25836046]
  [0.91518702 0.53411372 0.57493867 0.22082032]]]
(4, 2, 4)


In [236]:
a,b = np.dsplit(x,2)
print(a)
print(b)
print(a.shape)

[[[0.5751142  0.97912233]
  [0.5564332  0.59162577]
  [0.62499918 0.10851299]
  [0.17952721 0.47913767]]

 [[0.91726177 0.01036594]
  [0.71497769 0.85665516]
  [0.02860571 0.01699557]
  [0.60690178 0.9698497 ]]

 [[0.60484186 0.43502748]
  [0.15159298 0.25986192]
  [0.82142181 0.8921145 ]
  [0.56686112 0.63545784]]

 [[0.61579189 0.41850701]
  [0.06968443 0.01902491]
  [0.45929152 0.12146519]
  [0.91518702 0.53411372]]]
[[[0.93256729 0.18172034]
  [0.9294581  0.38454236]
  [0.83121866 0.45613941]
  [0.89873026 0.34462523]]

 [[0.6459295  0.84001229]
  [0.85462264 0.20167321]
  [0.9816342  0.88939763]
  [0.99770709 0.31927425]]

 [[0.13859491 0.00628637]
  [0.16676358 0.11380128]
  [0.30563692 0.68065345]
  [0.50748191 0.95516412]]

 [[0.6426856  0.45839306]
  [0.37600027 0.88664314]
  [0.23087077 0.25836046]
  [0.57493867 0.22082032]]]
(4, 4, 2)


In [238]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [240]:
y = np.flip(x,axis=0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [242]:
y = np.flip(x,axis=1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [244]:
y = np.flip(x,axis=-1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [246]:
y = np.fliplr(x)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [249]:
y = np.flipud(x)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [251]:
y = np.roll(x,8)
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [258]:
y = np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]


# Bitwise Operations on Array

In [260]:
x = np.array([0,1,0,1],np.uint8)
y = np.array([0,0,1,1],np.uint8)

print(np.bitwise_and(x,y))
print(np.bitwise_or(x,y))
print(np.bitwise_xor(x,y))
print(np.bitwise_not(x))

[0 0 0 1]
[0 1 1 1]
[0 1 1 0]
[255 254 255 254]


# Statistical Functions

In [261]:
x = np.random.randint(low=0,high=9,size=10)

In [263]:
print(np.median(x))
print(np.mean(x))
print(np.average(x))
print(np.std(x))
print(np.var(x))
print(np.histogram(x))

3.5
3.4
3.4
2.2449944320643644
5.039999999999998
(array([1, 2, 0, 2, 0, 2, 2, 0, 0, 1]), array([0. , 0.8, 1.6, 2.4, 3.2, 4. , 4.8, 5.6, 6.4, 7.2, 8. ]))
